version: "3.1"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: travellist-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - travellist
    db:
        image: mysql/mysql-server:latest-aarch64
        container_name: myapp-mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=myapp
            - MYSQL_DATABASE=myapp
            - MYSQL_USER=myapp
            - MYSQL_PASSWORD=myapp
        ports:
            - "8001:3306"
        networks:
            - travellist
    nginx:
        image: nginx:1.17-alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - travellist

networks:
    travellist:
        driver: bridge
